[build]
  command = "vite build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/dist/index.html"
  status = 200

[[redirects]]
  from = "/mobile/*"
  to = "/mobile/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"

[[headers]]
  for = "/mobile/*"
  [headers.values]
    cache-control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"

[[headers]]
  for = "/*.gltf"
  [headers.values]
    Content-Type = "model/gltf-binary"
