[[redirects]]
  # Redirect per la versione generale del sito (desktop)
  from = "/*"
  to = "/dist/:splat"
  status = 200

[[redirects]]
  # Redirect per la versione mobile del sito
  from = "/m/*"
  to = "/Brainiac/Mobile/:splat"
  status = 200

[build]
  command = "vite build"