[build]
  command = "vite build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/dist/index.html"
  status = 200

[[redirects]]
  from = "/mobile/*"
  to = "/mobile/index.html"
  status = 200

  [[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "no-store, no-cache, proxy-revalidate, max-age=0"

[[headers]]
  for = "/mobile/*"
    [headers.values]
    Cache-Control = "no-store, no-cache, proxy-revalidate, max-age=0"


[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "public, max-age=3600"
    Content-Type = "model/gltf-binary"
