[build]
  command = "npm run build" # o "yarn build" a seconda del package manager che utilizzi
  publish = "dist"
  
[[redirects]]
  from = "/*"
  to = "/dist/index.html"
  status = 200
  
[[redirects]]
  from = "/mobile/*"
  to = "/mobile/index.html"
  status = 200